use_frameworks!

platform :ios, '13.0'

target 'OttuCheckout_Example' do
  pod 'OttuCheckout', :path => '../'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa'
  target 'OttuCheckout_Tests' do
    inherit! :search_paths

    
  end
end
